Imported Upstream version 2.70

diff --git a/autoconf b/autoconf
--- a/autoconf
+++ b/autoconf
@@ -1,10 +1,18 @@
 
-#$Id: autoconf,v 2.15 92/01/31 13:01:34 berg Rel $
+#$Id: autoconf,v 2.20 1992/04/29 16:38:45 berg Exp $
 
-SHELL=/bin/sh || exec /bin/sh autoconf $* # we're in a csh, feed myself to sh
+SHELL=$4 || exec $4 autoconf $* # we're in a csh, feed myself to sh
 
 # All possible entries in autoconf.h:
 
+#	#define UNISTD_H_MISSING
+#	#define STDDEF_H_MISSING
+#	#define STDLIB_H_MISSING
+#	#define SYS_WAIT_H_MISSING
+#	#define SYS_UTSNAME_H_MISSING
+#	#define STRING_H_MISSING
+#	#define SYSEXITS_H_MISSING
+#	#define SYS_FILE_H_MISSING
 #	#define const
 #	#define volatile
 #	#define void char
@@ -16,43 +24,52 @@ SHELL=/bin/sh || exec /bin/sh autoconf $* # we're in a csh, feed myself to sh
 #	typedef long time_t;
 #	#define NOmemmove
 #	#define NObcopy
-#	#define NOstrstr
 #	#define NOstrcspn
 #	#define NOstrpbrk
 #	#define NOrename
 #	#define strchr(s,c) index(s,c)
 #	#define endpwent()
+#	#define endgrent()
 #	#define strtol(str,ptr,base) ((long)atoi(str))
+#	#define WMACROS_NON_POSIX
 #	#define oBRAIN_DAMAGE
 #	#define SMALLHEAP
 #	#define SYSTEM_MAILBOX "/usr/spool/mail/$USER"
 #	#define SENDMAIL "/usr/lib/sendmail"
 
-# A conforming ANSI compiler and POSIX library should only produce four
-# entries in autoconf.h: endpwent(), rename(), SYSTEM_MAILBOX, SENDMAIL (and
-# perhaps SMALLHEAP)
+# A conforming ANSI compiler and POSIX library should only produce six
+# entries in autoconf.h: SYS_FILE_H_MISSING, endpwent(), endgrent(), rename(),
+# SYSTEM_MAILBOX, SENDMAIL (and perhaps SMALLHEAP)
 # Anything else indicates failure of your installation to comply with either
 # the ANSI or POSIX standards (but procmail should be installable anyway).
 
 PATH=:$PATH
 ACONF=$3
-MAKE=$2
+MAKE="$2"
+RM="$5"
+USRINC=$6
 DEVNULL=/dev/null
-export SHELL
+export SHELL PATH
 if test -f $ACONF
 then
  trap "exit 1" 1 2 3 15
 else
- trap "rm -f $ACONF; exit 1" 1 2 3 15
+ trap "$RM $ACONF; exit 1" 1 2 3 15
+fi
+
+if test -n "$LD_LIBRARY_PATH"
+then
+ echo '***************************** WARNING *********************************'
+ echo '* You seem to have set the LD_LIBRARY_PATH variable, this might cause *'
+ echo '* some trouble during the execution of this autoconf script.  If you  *'
+ echo '* encounter errors about "_autotst not found" or any other	     *'
+ echo '* irregularities, stop the make, do a: "make clean",		     *'
+ echo '* clear LD_LIBRARY_PATH from the environment, and start over.	     *'
+ echo '***************************** WARNING *********************************'
 fi
 
 cat >grepfor <<HERE
-if fgrep "\$1" _autotst.rrr >$DEVNULL
-then
- echo "\$2" >>$ACONF
- exit 0
-fi
-exit 1
+fgrep -e "\$1" _autotst.rrr >$DEVNULL && echo "\$2" >>$ACONF
 HERE
 chmod 0755 grepfor
 
@@ -60,6 +77,15 @@ cat >$ACONF <<HERE
 /* This file was automagically generated by autoconf */
 
 HERE
+
+test -f $USRINC/unistd.h || echo "#define UNISTD_H_MISSING" >>$ACONF
+test -f $USRINC/stddef.h || echo "#define STDDEF_H_MISSING" >>$ACONF
+test -f $USRINC/stdlib.h || echo "#define STDLIB_H_MISSING" >>$ACONF
+test -f $USRINC/sys/wait.h || echo "#define SYS_WAIT_H_MISSING" >>$ACONF
+test -f $USRINC/sys/utsname.h || echo "#define SYS_UTSNAME_H_MISSING" >>$ACONF
+test -f $USRINC/string.h || echo "#define STRING_H_MISSING" >>$ACONF
+test -f $USRINC/sysexits.h || echo "#define SYSEXITS_H_MISSING" >>$ACONF
+test -f $USRINC/sys/file.h || echo "#define SYS_FILE_H_MISSING" >>$ACONF
 
 # WARNING: in ./include/stdlib.h the const keyword is already used!
 #	   hence the const test has to precede all others.
@@ -78,7 +104,7 @@ then
 else
  echo '#define const' >>$ACONF
 fi
-rm -f _autotst.$1
+${RM} _autotst.$1
 
 cat >_autotst.c <<HERE
 main(){volatile int i;return(i=0);}
@@ -91,7 +117,7 @@ then
 else
  echo '#define volatile' >>$ACONF
 fi
-rm -f _autotst.$1
+${RM} _autotst.$1
 
 cat >_autotst.c <<HERE
 #include "includes.h"
@@ -109,7 +135,7 @@ HERE
 
 echo 'Testing for void*,size_t,pid_t,time_t,mode_t,uid_t,gid_t'
 ${MAKE} _autotst.$1 >_autotst.rrr 2>&1
-rm -f _autotst.$1
+${RM} _autotst.$1
 
 grepfor void '#define void char'
 grepfor size_t 'typedef unsigned size_t;'
@@ -121,27 +147,46 @@ grepfor gid_t 'typedef int gid_t;'
 
 cat >_autotst.c <<HERE
 #include "includes.h"
+main(){int i;i=1;
+ i+=WIFEXITED(i);
+ i+=WIFSTOPPED(i);
+ i+=WEXITSTATUS(i);
+ return i;}
+HERE
+
+echo 'Testing for WIFEXITED(), WIFSTOPPED() & WEXITSTATUS()'
+if ${MAKE} _autotst.$1 >_autotst.rrr 2>&1
+then
+   grepfor struct '#define WMACROS_NON_POSIX' ||
+    grepfor union '#define WMACROS_NON_POSIX'
+else
+   echo '#define WMACROS_NON_POSIX' >>$ACONF
+fi
+${RM} _autotst.$1
+
+cat >_autotst.c <<HERE
+#include "includes.h"
 main(){char a[2];
- endpwent();memmove(a,"0",1);bcopy("0",a,1);strstr(a,"0");strcspn(a,"0");
+ endpwent();endgrent();memmove(a,"0",1);bcopy("0",a,1);strcspn(a,"0");
  strtol("0",(char**)0,10);strchr("0",'0');strpbrk(a,"0");rename(a,"0");
  return 0;}
 HERE
 
-echo 'Testing for memmove, strstr, strchr, strcspn & strtol'
+echo 'Testing for memmove, strchr, strpbrk, strcspn & strtol'
 ${MAKE} _autotst.$1 >$DEVNULL 2>&1
 ${MAKE} _autotst >_autotst.rrr 2>&1
-rm -f _autotst _autotst.$1
+${RM} _autotst _autotst.$1
 
-grepfor strstr '#define NOstrstr'
 grepfor strcspn '#define NOstrcspn'
 grepfor strpbrk '#define NOstrpbrk'
 grepfor rename '#define NOrename'
 grepfor strchr '#define strchr(s,c) index(s,c)'
 grepfor setpwent '#define setpwent()'
 grepfor endpwent '#define endpwent()'
+grepfor endgrent '#define endgrent()'
 grepfor strtol '#define strtol(str,ptr,base) ((long)atoi(str))'
 grepfor memmove '#define NOmemmove' &&
-if fgrep bcopy _autotst.rrr >$DEVNULL
+if fgrep -e bcopy _autotst.rrr >$DEVNULL
 then
  echo '#define NObcopy' >>$ACONF
 
@@ -159,7 +204,7 @@ HERE
     echo 'Yep, it is'			# ISC chokes on its own offsetof()
     echo '#define oBRAIN_DAMAGE' >>$ACONF
  fi
- rm -f _autotst.$1
+ ${RM} _autotst.$1
 
 else
 
@@ -182,7 +227,7 @@ HERE
    echo 'Sorry, incompetent bcopy'
    echo '#define NObcopy' >>$ACONF
  fi
- rm -f _autotst
+ ${RM} _autotst
 fi
 
 cat >_autotst.c <<HERE
@@ -198,7 +243,7 @@ echo 'Determining the most applicable block size'
 
 ${MAKE} _autotst >$DEVNULL 2>&1
 _autotst >>$ACONF
-rm -f _autotst
+${RM} _autotst
 
 if test -d /usr/spool/mail
 then
@@ -213,7 +258,7 @@ fi
 
 cat >lookfor <<HERE
 for a in /usr/lib /lib /usr/etc /etc /usr/bin /bin /usr/local/bin /usr/lbin \
-/usr/local/lib /usr/local
+ /usr/local/lib /usr/local /usr/.lib
 do
  if test -f "\$a/\$1"
  then
@@ -237,7 +282,7 @@ else
  echo "#define SENDMAIL \"$a\"" >>$ACONF
 fi
 
-rm -f _autotst* lookfor grepfor
+${RM} _autotst* lookfor grepfor
 
 echo -----------------------------autoconf.h-----------------------------------
 cat $ACONF >&2
