Imported Upstream version 3.12

diff --git a/initmake b/initmake
--- a/initmake
+++ b/initmake
@@ -1,7 +1,7 @@
 #! /bin/sh
 :
-# Copyright (c) 1992-1994, S.R. van den Berg, The Netherlands
-#$Id: initmake,v 1.61 1994/09/27 15:03:16 berg Exp $
+# Copyright (c) 1992-1999, S.R. van den Berg, The Netherlands
+#$Id: initmake,v 1.70 1999/02/16 21:13:32 guenther Exp $
 
 if test -z "$IFS"
 then IFS=" \
@@ -23,7 +23,7 @@ else
   case "$BSHELL" in
      *zsh*) ;;
      *) echo "(If I wouldn't know better, I'd say you're trying to sell"
-	echo "me a buggy zsh :-)" ;;
+	echo "me an incompatible zsh :-)" ;;
   esac
   echo "Please edit the Makefile and try setting BSHELL to a shell which"
   echo "is more backwards compatible with a Bourne, Korn or POSIX shell."
@@ -46,7 +46,7 @@ shift; BINSS="$1"
 shift; MANS1S="$1"
 shift; MANS5S="$1"
 shift; SUBDIRS="$1"
-shift; BINDIR="$1"
+shift; VISIBLE_BINDIR="$1"
 
 test 1 != $# &&
  echo "Don't start this script directly, use \`make init'" && exit 1
@@ -55,17 +55,7 @@ test -z "$MSHELL" || SHELL=$MSHELL
 case "$SHELL" in
   *sh*)
      case "$SHELL" in
-	*csh*) echo "Warning: really perverted make detected"; SHELL="";;
-	*zsh*) $RM src/_autotst
-	    $SHELL <<HERE
-	    O="echo test >src/_autotst"
-	    exec 2>$DEVNULL
-	    \$O
-HERE
-	   if test ! -f src/_autotst
-	   then
-	      echo "Warning: your $SHELL is broken, avoiding it"; SHELL=""
-	   fi ;;
+	*[zc]sh*) echo "Warning: really perverted make detected"; SHELL="";;
      esac
      if test ! -z "$SHELL"
      then
@@ -104,13 +94,18 @@ then
   exit 2
 fi
 
+case a in
+  [!a]) classok=no ;;		# This shell is *very* old
+  *) classok=yes ;;
+esac
+
 if test ! -z "$LD_LIBRARY_PATH"
 then
   echo '***************************** WARNING *********************************'
   echo '* You seem to have set the LD_LIBRARY_PATH variable, this might cause *'
-  echo '* some trouble during the execution of this autoconf script.  If the  *'
-  echo '* the make does not finish by itself, do a: "make clean",	      *'
-  echo '* clear LD_LIBRARY_PATH from the environment, and start over.	      *'
+  echo '* some trouble during the compilation of this package.	If the make   *'
+  echo '* does not finish by itself, do a: "make clean", clear		      *'
+  echo '* LD_LIBRARY_PATH from the environment, and start over.		      *'
   echo '***************************** WARNING *********************************'
 fi
 
@@ -203,7 +198,7 @@ else
 fi
 $cc $CFLAGS1 $CFLAGS _autotst.$O -o _autotst $LDFLAGS1 -lc >_autotst.rrr 2>&1 \
  && if grep "[\"']c['\"]" _autotst.rrr >$DEVNULL ||
-   fgrep libc _autotst.rrr >$DEVNULL
+   $FGREP libc _autotst.rrr >$DEVNULL
   then
   :
   else
@@ -213,16 +208,24 @@ $cc $CFLAGS1 $CFLAGS _autotst.$O -o _autotst $LDFLAGS1 -lc >_autotst.rrr 2>&1 \
 LDFLAGS="$SEARCHLIBS"
 firstrun=yes
 checkpath=no
+runcombination=no
 
 while $RM _autotst
  $cc $CFLAGS1 $CFLAGS _autotst.$O -o _autotst $LDFLAGS1 $LDFLAGS \
   $LDFLAGSC >_autotst.rrr 2>&1 || firstrun=yes
  test $firstrun = yes -o ! -f _autotst
 do
-  set dummy $LDFLAGS
-  shift
-  echo 2>&1 "	...scanning for $# libraries..."
-  NEWLDFLAGS=""
+  if test $runcombination = yes
+  then
+     LDFLAGS=""
+     read NEWLDFLAGS 0>&9
+     echo 2>&1 " ...trying $NEWLDFLAGS"
+  else
+     set dummy $LDFLAGS
+     shift
+     echo 2>&1 "	...scanning for $# libraries..."
+     NEWLDFLAGS=""
+  fi
   for lib in `echo _dummy_ $LDFLAGS | sed -e s/-l//g`
   do
      if test _dummy_ != $lib
@@ -231,10 +234,27 @@ do
 	 ( exec <_autotst.rrr
 	   while read b
 	   do
-	      case ":$b:" in
-		 *$cc*_autotst.$O*) ;;
-		 *lib$lib[!a-z_]*|*$a[!a-z_]*|*[!a-z]$lib[!a-z_]*) exit 1;;
-	      esac
+	      if test $classok = yes
+	      then
+		 case ":$b:" in
+		    *$cc*_autotst.$O*) ;;
+		    *"not used for resolving"*) ;;
+		    *lib$lib[!a-z_]*|*$a[!a-z_]*|*[!a-z]$lib[!a-z_]*) exit 1;;
+		 esac
+	      else
+		 case ":$b:" in
+		    *$cc*_autotst.$O*) ;;
+		    *"not used for resolving"*) ;;
+		    *) for c in $b
+		       do
+			  case ":$c:" in
+			     *lib$lib[a-z_]*|*$a[a-z_]*|\
+			      *[a-z]$lib*|*$lib[a-z_]*) ;;
+			     *$a*|*$lib*) exit 1;;
+			  esac
+		       done ;;
+		 esac
+	      fi
 	   done
 	   exit 0
 	 )
@@ -260,21 +280,67 @@ do
   then
      if test $checkpath = yes
      then
-	echo 2>&1 "Whoeaaa!  There's something fishy going on here."
-	echo 2>&1 "You have a look and see if you detect anything uncanny:"
-	echo 2>&1 "*******************************************************"
-	cat 2>&1 _autotst.rrr
-	echo 2>&1 "*******************************************************"
-	echo 2>&1 \
+	if test $runcombination = yes
+	then
+	   echo 2>&1 "Whoeaaa!	There's something fishy going on here."
+	   echo 2>&1 "You have a look and see if you detect anything uncanny:"
+	   echo 2>&1 "*******************************************************"
+	   echo \ $cc $CFLAGS1 $CFLAGS _autotst.$O -o _autotst $LDFLAGS1\
+	    $LDFLAGS >>_autotst.rrr
+	   echo "	$LDFLAGSC" >>_autotst.rrr
+	   cat 2>&1 _autotst.rrr
+	   echo 2>&1 "*******************************************************"
+	   echo 2>&1 \
        "I suggest you take a look at the definition of LDFLAGS* and SEARCHLIBS"
-	echo 2>&1 "in the Makefile before you try make again."
-	echo 2>&1 \
-	 "Also: write me a mail showing the errorlog you just generated."
-	echo 2>&1 "The errorlog can still be found in src/_autotst.rrr"
-	echo 2>&1 \
-	 "It would be helpful if you could mention what machine and OS"
-	echo 2>&1 "you are trying to compile this on (uname -a).  Thanks."
-	exit 1
+	   echo 2>&1 "in the Makefile before you try make again."
+	   echo 2>&1 \
+	    "Also: write me a mail showing the errorlog you just generated."
+	   echo 2>&1 "The errorlog can still be found in src/_autotst.rrr"
+	   echo 2>&1 \
+	    "It would be helpful if you could mention what machine and OS"
+	   echo 2>&1 "you are trying to compile this on (uname -a).  Thanks."
+	   exit 1
+	fi
+	echo 2>&1 "Inconsistent libraries found, trying to accomodate..."
+	runcombination=yes
+	cat >_autotst <<\HERE
+#!/bin/sh
+
+exec awk '
+ { split($0,lib);
+   nf=0;
+   for(a in lib)
+      nf++;
+   p[0]=nf;
+   while(!p[nf-1])
+    { for(j=i=0;p[i];i++)
+	 while(++j<p[i])
+	    printf(" %s",lib[j]);
+      while(++j<=nf)
+	 printf(" %s",lib[j]);
+      printf("\n");
+      for(k=0;;k++)
+       { if(!p[k])
+	  { p[k]=nf;
+	    break;
+	  }
+	 if(p[k]!=k+1)
+	  { --p[k];
+	    break;
+	  }
+       }
+      while(--k>=0)
+	 p[k]=p[k+1]-1;
+    }
+   exit;
+ }'
+HERE
+	chmod 755 _autotst
+	echo " $LDFLAGS" | ./_autotst >_autotst.lst
+	echo "" >>_autotst.lst
+	exec 8<&0 <_autotst.lst 9<&0 0<&8 8<&-
+	read NEWLDFLAGS 0<&9
+	echo 2>&1 " ...trying $NEWLDFLAGS"
      fi
      checkpath=yes
   else
@@ -284,7 +350,7 @@ do
   firstrun=no
 done
 
-$RM _autotst.$O _autotst.c _autotst
+$RM _autotst.$O _autotst.c _autotst _autotst.rrr _autotst.lst
 cd ..			# returning to the main procmail directory ######
 
 LDFLAGS="$LDFLAGS$LDFLAGSC"
@@ -363,7 +429,7 @@ do
   cat $a/Makefile.0 >>$a/_Makefile
 done
 
-echo "BINDIR=$BINDIR"					>>src/_Makefile
+echo "VISIBLE_BINDIR=$VISIBLE_BINDIR"			>>src/_Makefile
 
 for a in $BINSS
 do
@@ -378,7 +444,7 @@ for a in $MANSS
 do
   echo							>>man/_Makefile
   echo "../new/$a: $a ../config.check"			>>man/_Makefile
-  echo "	@test -d ../new || mkdir ../new"	>>src/_Makefile
+  echo "	@test -d ../new || mkdir ../new"	>>man/_Makefile
   echo "	@\$(RM) \$@"				>>man/_Makefile
   echo "	\$(LN) ../man/$a \$@"			>>man/_Makefile
 done
diff --git a/src/autoconf b/src/autoconf
--- a/src/autoconf
+++ b/src/autoconf
@@ -1,7 +1,7 @@
 #! /bin/sh
 :
-# Copyright (c) 1990-1994, S.R. van den Berg, The Netherlands
-#$Id: autoconf,v 1.102 1994/10/18 14:30:01 berg Exp $
+# Copyright (c) 1990-1997, S.R. van den Berg, The Netherlands
+#$Id: autoconf,v 1.120 1999/01/20 17:58:20 guenther Exp $
 
 # All possible entries in autoconf.h:
 
@@ -42,6 +42,9 @@
 #	#define NOsetegid
 #	#define NOsetregid
 #	#define NOsetresgid
+#	#define setrgid_BRAIN_DAMAGE
+#	#define setrgid_RUNTIME_CHECK
+#Ok	#define TOGGLE_SGID_OK
 #	#define NOpow
 #	#define NOmkdir
 #	#define NOfstat
@@ -52,7 +55,7 @@
 #	#define SLOWstrstr
 #Ok	#define CAN_chown
 #	#define strchr(s,c) index(s,c)
-#	#define initgroups(n,g)
+#	#define NOinitgroups
 #Ok	#define endpwent()
 #Ok	#define endgrent()
 #Ok	#define endhostent()
@@ -74,10 +77,14 @@
 #	#define NOfcntl_lock
 #Ok	#define USElockf
 #Ok	#define USEflock
-#Ok	#define SYSTEM_MAILBOX "/usr/spool/mail/$LOGNAME"
-#Ok	#define SENDMAIL "/usr/lib/sendmail"
+#Ok	#define MAILSPOOLDIR "/var/spool/mail/"
+#Ok	#define SENDMAIL "/usr/sbin/sendmail"
+#	#define buggy_SENDMAIL
+#	#define DEFflagsendmail ""
 #Ok	#define CF_no_procmail_yet
 #Ok	#define defPATH "PATH=$HOME/bin:/bin:/usr/bin:/usr/local/bin"
+#Ok	#define INEFFICIENTrealloc
+#Ok	#define PM_VERSION "n.nn"
 
 # A conforming ANSI compiler and POSIX library should not have any defines not
 # marked as "Ok" in the autoconf.h file.
@@ -140,13 +147,13 @@ HERE
   trap "kill \`cat _locktst.pid\` 2>$DEVNULL;cp $ACONF $ACONF.tmp
    test ! -z \"\$OLDTESTDIRS\" && $RM -r \$OLDTESTDIRS \$OLDTESTDIRS 2>$DEVNULL
    test ! -z \"\$tailpid\" && kill \$tailpid 2>$DEVNULL
-   kill \`cat _locktst.pid\` 2>$DEVNULL; exit 1" 1 2 3 15
+   kill \`cat _locktst.pid\` 2>$DEVNULL; exit 1" 1 2 3 13 15
 else
   trap "kill \`cat _locktst.pid\` 2>$DEVNULL;$RM -r $ACONF.tmp
    test ! -z \"\$OLDTESTDIRS\" && $RM -r \$OLDTESTDIRS \$OLDTESTDIRS 2>$DEVNULL
    mv $ACONF $ACONF.tmp 2>$DEVNULL
    test ! -z \"\$tailpid\" && kill \$tailpid 2>$DEVNULL
-   kill \`cat _locktst.pid\` 2>$DEVNULL; exit 1" 1 2 3 15
+   kill \`cat _locktst.pid\` 2>$DEVNULL; exit 1" 1 2 3 13 15
 fi
 
 nocore=yes
@@ -167,7 +174,7 @@ more information about this, READ PARAGRAPH TWO in INSTALL).  To suppress this
 prompt you can set the LOCKINGTEST variable in the Makefile.
 
 Please add writable directories to the list.  You should only add directories
-that reside on filesystems that have unique characterics.  E.g. if you have
+that reside on filesystems that have unique characteristics.  E.g. if you have
 several remote NFS partitions, pick some unique client-server pairs, there is
 little use in picking the same server twice from the same client-machine.
 An excellent candidate would be a remotely mounted mail spool directory.
@@ -177,7 +184,7 @@ HERE
 testdirs="/tmp ."
 
 case "$LOCKINGTEST" in
-  ""|*[!0-9]*) b=dummy;;
+  ""|*[a-zA-Z/]*) b=dummy ;;
   *) b=""; testdirs=$LOCKINGTEST; LOCKINGTEST=dummy ;;
 esac
 
@@ -253,24 +260,25 @@ main(){int i=0;char*p="t";
  {off_t voff_t;i+=voff_t=1;}
  return !vvoid+!i;}
 #include <unistd.h>
-struct {char a;char b;} setsid;
+empty()
+{ setsid();
+}
 HERE
 
 if $MAKE _autotst.$O 2>&1 | $FGREP -v include/ >_autotst.rrr
  test -f _autotst.$O
 then
-  echo "#define setsid()" >>_locktst.h
+  $MAKE _autotst >$DEVNULL 2>&1 || echo "#define setsid()" >>_locktst.h
 else
   grepfor void '#define void char'
   grepfor time_t 'typedef long time_t;'
   grepfor off_t 'typedef long off_t;'
-  if $FGREP setsid _autotst.rrr >$DEVNULL 2>&1
+  if $MAKE _autotst.$O >$DEVNULL 2>&1
   then
-  :
+     $MAKE _autotst >$DEVNULL 2>&1 || echo "#define setsid()" >>_locktst.h
   else
+     echo "#define UNISTD_H_MISSING" >>$ACONF
      echo "#define setsid()" >>_locktst.h
-     $MAKE _autotst.$O >$DEVNULL 2>&1
-     test -f _autotst.$O || echo "#define UNISTD_H_MISSING" >>$ACONF
   fi
 fi
 
@@ -417,7 +425,7 @@ unsigned sfork()
 }
 
 main(argc,argv)char*argv[];
-{ int goodlock,testlock,i,pip[2],pipw[2];unsigned otimet,dtimet;
+{ int goodlock,testlock,i,pip[2],pipw[2];time_t otimet;unsigned dtimet;
   static char filename[]="_locktst.l0";
   close(0);goodlock=0;testlock=FIRST_lock;signal(SIGPIPE,SIG_DFL);
   if(argc==2)
@@ -510,7 +518,7 @@ which program, XX indicates a lock conflict or failure\n");
 	   for(j=NR_of_lockfiles;lckdfil[--j]=0,j;);
 	   timeout=0;sleep(1);read(pipw[0],&curflag,1);close(pipw[0]);
 	   kill(ppid,SIGKILL);fdcollect=pip[0];signal(SIGALRM,stimeout);
-	   dtimet=(((unsigned)time((time_t*)0)-otimet)*GROW)+TIME_OUT_SEC;
+	   dtimet=(time((time_t*)0)-otimet)*GROW+TIME_OUT_SEC;
 	   do
 	    { unlink("_locktst.alive");alarm(dtimet+2);		 /* watchdog */
 	      dtimet=(otimet=time((time_t*)0)-otimet)>dtimet?
@@ -658,7 +666,7 @@ echo "" >_locktst.pid
 $MV _autotst _locktst
 
 case "$testdirs" in
-  *[!0-9]*)
+  *[a-zA-Z/]*)
      for b in $TESTDIRS
      do
 	for a in 0 1 2 3
@@ -679,29 +687,48 @@ cat >_autotst.c <<HERE
 #ifndef UNISTD_H_MISSING
 #include <unistd.h>		/* execvp() */
 #endif
+int a(b)const int b[];
+{ return *++b;				  /* watcom 10.6 on QNX refuses this */
+}
 main()
 { char r[]="",*const*p;char*q="";const char*s="";
   static const char*const nullp,*const*d= &nullp;	/* AIX 3.2.3 failure */
   static struct{const int a;int b;}c[2];
   --(c+1)->b;				 /* AIX 3.1.5 machines can't do this */
   p= &q;
-  if(!*d&&c[1].b)		      /* some magic to confuse the optimiser */
-     d=(const char*const*)p;		  /* so that it can't complain about */
-  else				    /* about the uselessness of this program */
-     execvp(q,p); /* IRIX 4.0.1 system-include files are wrong on this point */
+  ;{ int pip[2];
+     pipe(pip);
+     if(fork())		       /* this should hide core dumps from the shell */
+      { close(pip[1]);				    /* close the writing end */
+	return 1==read(pip[0],r,1)?0:1;		   /* wait for the rendevouz */
+      }
+     close(pip[0]);				    /* close the writing end */
+     if(!*d&&c[1].b)		      /* some magic to confuse the optimiser */
+	d=(const char*const*)p;		     /* core dumps Ultrix 4.3 ANSI C */
+     else /* so that it can't complain about the uselessness of this program */
+	execvp(q,p);   /* IRIX 4.0.1 system-includes are wrong on this point */
+     if(write(pip[1],r,1)!=1)		      /* notify mam that we survived */
+	return 1;				   /* oops, lost mam somehow */
+   }
   return r==s;		    /* Domain/OS warns here, not about "r==s" though */
 }
 HERE
 
 echo 'Testing for const'
 if $MAKE _autotst.$O 2>&1 | $FGREP -v include/ >_autotst.rrr
- test -f _autotst.$O
+  test -f _autotst.$O && $MAKE _autotst >$DEVNULL 2>&1 && _autotst
 then
   grepfor const '#define NO_const'
 else
   echo '#define NO_const' >>$ACONF
+  set dummy *core*
+  if test -f $2 -a $nocore = yes
+  then
+     echo "Removing core file (bogus readonly segment)"
+     $RM *core*
+  fi
 fi
-$RM _autotst.$O
+$RM _autotst.$O _autotst
 
 cat >_autotst.c <<HERE
 main(){volatile int i;return (i=0);}
@@ -740,7 +767,8 @@ cat >_autotst.c <<HERE
 #include "includes.h"
 int a;
 #ifndef SYS_DIRENT_H_MISSING
-DIR*vDIR;
+typedef DIR*tDIR;
+tDIR vDIR;
 #endif
 HERE
 
@@ -866,6 +894,55 @@ done
 $RM _autotst.$O
 
 cat >_autotst.c <<HERE
+#include "$ACONF"
+#include "../config.h"
+#include <stdio.h>
+#ifndef STDLIB_H_MISSING
+#include <stdlib.h>
+#define INITIAL 60
+#else
+void*realloc();
+#endif
+int main()
+{ char*p=0,*q=0;
+  size_t len,last,max=BLKSIZ*64;	      /* 1M on non-SMALLHEAP systems */
+  int count= -1;		     /* take into account the initial malloc */
+  for(last=len=INITIAL;len<=max+INITIAL;len+=BLKSIZ)
+   { if(!(p=realloc(p,len)))
+	break;
+     if(p!=q)
+	count++,q=p,fprintf(stderr,"len=%lu p=%p\n",(unsigned long)len,p);
+     for(;last<len;last+=1024)		    /* touch at least every new page */
+	p[last]=last%127;
+   }
+  free(q);
+  printf("/* %d move%s in %d steps of size %d when reallocing */\n",
+	 count,count==1?"":"s",(int)(max/BLKSIZ),BLKSIZ);
+  if(BLKSIZ*(10*count+1)>max)
+   { puts("#define INEFFICIENTrealloc");
+     exit(1);
+   }
+  exit(0);
+}
+HERE
+
+echo 'Checking realloc implementation'
+
+if $MAKE _autotst >$DEVNULL 2>&1
+ test -f _autotst
+then
+ _autotst >_autotst.rrr 2>realloc.log
+ case "$?" in
+ 0) cat _autotst.rrr >>$ACONF;;
+ 1) cat _autotst.rrr >>$ACONF
+    echo 'Sorry, repeatedly reallocing is inefficient';;
+ *) echo "The test program failed somehow.  Assuming realloc is fine";;
+ esac
+fi
+
+$RM _autotst.$O _autotst _autotst.rrr
+
+cat >_autotst.c <<HERE
 #include "includes.h"
 main(){int i;i=1;
  i+=WIFEXITED(i);
@@ -876,14 +953,16 @@ main(){int i;i=1;
 HERE
 
 echo 'Testing for WIFEXITED(), WIFSTOPPED(), WEXITSTATUS() & WSIGTERM()'
-if $MAKE _autotst.$O 2>&1 | $FGREP -v include/ >_autotst.rrr
+if $MAKE _autotst.$O >_autotst.rrr 2>&1
 then
+   $FGREP -v include/ <_autotst.rrr >_autotst.$O
+   $MV _autotst.$O _autotst.rrr
    grepfor struct '#define WMACROS_NON_POSIX' ||
     grepfor union '#define WMACROS_NON_POSIX'
 else
    echo '#define WMACROS_NON_POSIX' >>$ACONF
 fi
-$RM _autotst.$O
+$RM _autotst.$O _autotst.rrr
 
 cat >_autotst.c <<HERE
 #include "includes.h"
@@ -937,7 +1016,7 @@ grepfor opendir "
 grepfor rename '#define NOrename'
 a=no
 grepfor setrgid '#define NOsetrgid' && a=yes
-if grepfor setrgid '#define NOsetegid' || test $a = yes
+if grepfor setegid '#define NOsetegid' || test $a = yes
 then
   grepfor setregid '#define NOsetregid' &&
    grepfor setresgid '#define NOsetresgid'
@@ -949,7 +1028,7 @@ grepfor strchr '#define strchr(s,c) index(s,c)'
 grepfor uname "\
 #define NOuname		  \
 /* <sys/utsname.h> defines it, the libraries don't */"
-grepfor initgroups '#define initgroups(n,g)'
+grepfor initgroups '#define NOinitgroups'
 grepfor endpwent '#define endpwent()'
 grepfor endgrent '#define endgrent()'
 if grepfor gethostbyname '#define NO_COMSAT'
@@ -1014,7 +1093,7 @@ fi
 $FGREP -e LD_ /bin/ld >/dev/null 2>&1 && echo "#define LD_ENV_FIX" >>$ACONF
 test -f /bin/test && echo "#define GOT_bin_test" >>$ACONF
 
-cat >_autotst.c <<HERE
+cat >_autotst.c <<\HERE
 #define BENCHSIZE	16384
 #define GRANULARITY	64		    /* maximal benchmark granularity */
 #include "sublib.c"
@@ -1064,7 +1143,7 @@ main(argc,argv)int argc;const char*argv[];
 /* Your system's strstr() is %.2f times %sER than my C-routine */\n",
 	 syscnt>=iter?(double)syscnt/iter:(double)iter/syscnt,
 	 syscnt>=iter?"SLOW":"FAST");
-	if(syscnt>=iter&&syscnt>1)
+	if(syscnt>iter+iter/16)		  /* if at least 1.0625 times slower */
 	   printf("\
 #define SLOWstrstr\t\t\t      /* using my substitute instead */\n");
       }
@@ -1116,26 +1195,54 @@ main(argc,argv)int argc;const char*argv[];
      ;{ struct passwd*p;
 	if(sizeof(int)>sizeof(uid_t)&&(p=getpwnam("root"))&&(*p->pw_dir!='/'||
 	 (*p->pw_shell&&!(p->pw_shell)[1])))
-	   puts("#define _GUID_T\ntypedef int uid_t;\ntypedef int gid_t;");
+	 { puts("#define _GUID_T\ntypedef int uid_t;\ntypedef int gid_t;");
+	   goto skipsetrgid;
+	 }
       }
 #endif
-   }
-#ifdef SYSTEM_MBOX
-  if(argc==2)
-   { printf("#define SYSTEM_MAILBOX %s\n",SYSTEM_MBOX);
-     return 1;
-   }
+#ifndef NOinitgroups
+     if(geteuid()==ROOT_uid)
+      { setgid(2);
+	if(!setrgid(3)&&(getgid()!=3||getegid()!=2))
+	   puts("#define setrgid_BRAIN_DAMAGE");
+	else
+	 { setuid(2);
+	   if(!setgid(3)&&!setgid(2))
+	      puts("#define TOGGLE_SGID_OK");
+	 }
+      }
+     else
+#ifndef NGROUPS_MAX			 /* is this safeguard really needed? */
+#define NGROUPS_MAX	3
+#endif				       /* some OSes expect an array of ints? */
+      { gid_t groups[NGROUPS_MAX*sizeof(int)/sizeof(gid_t)];unsigned i;
+	for(i=getgroups(NGROUPS_MAX,groups);
+	    --i<NGROUPS_MAX&&groups[i]==getgid(););
+	if(i<NGROUPS_MAX)
+	 { setegid(groups[i]);
+	   if(!setrgid(groups[i])&&getgid()!=groups[i])
+	      puts("#define setrgid_BRAIN_DAMAGE");
+	 }
+	else
+	   puts("#define setrgid_RUNTIME_CHECK");
+      }
 #endif
+skipsetrgid:;
+   }
 #ifdef DEFsendmail
   if(argc==3)
-   { printf("#define SENDMAIL %s\n",DEFsendmail);
+   { printf("#define SENDMAIL \"%s\"\n",DEFsendmail);
      return 1;
    }
 #endif
   if(argc==4)
-   { FILE*fp;
-     setuid(2);fp=fopen(argv[1],"w");fclose(fp);
-     if(!chown(argv[1],geteuid()==3?4:3,getegid()))
+   { FILE*fp;					      /* in case we are root */
+     chown(argv[1],2,getegid());setuid(2);     /* adjust the directory first */
+     if(!(fp=fopen(argv[2],"w")))
+	goto openerr;				 /* shouldn't happen, really */
+     fclose(fp);			   /* always clean up after yourself */
+     if(!chown(argv[2],geteuid()==3?4:3,getegid()))
+openerr:
 	printf("#define CAN_chown\n");
    }
   if(argc>4)
@@ -1187,8 +1294,8 @@ main(argc,argv)int argc;const char*argv[];
 	sprintf(num,"%u",newdiff);nargv[argc+diff]=0;  /* pass on the target */
 	execv(argv[0],nargv);					/* jeronimo! */
       }
-printit:					   /* we proudly present the */
-     printf("#define MAX_argc %d%s\n",argc-2,einfo); /* results of the jury! */
+printit:				  /* we proudly present the findings */
+     printf("#define MAX_argc %d%s\n",argc-2,einfo);	     /* of the jury! */
    }
   return EXIT_SUCCESS;
 }
@@ -1207,7 +1314,7 @@ else
   echo 2>&1 "*******************************************************"
   cat 2>&1 _autotst.rrr
   echo 2>&1 "*******************************************************"
-  echo 2>&1 "I suggest you take a look at the definition of LDLAGS*"
+  echo 2>&1 "I suggest you take a look at the definition of LDFLAGS*"
   echo 2>&1 "in the Makefile before you try make again."
   kill -15 $$
 fi
@@ -1219,24 +1326,25 @@ echo "Benchmarking your system's strstr() implementation"
 _autotst >>$ACONF
 
 found=no
-for a in /usr/spool/mail /usr/mail /var/spool/mail /var/mail /spool/mail
+
+for a in /var/spool/mail /usr/spool/mail /var/mail /usr/mail /spool/mail
 do
   test -d $a -a $found != yes &&
-   echo '#define SYSTEM_MAILBOX "'$a'/$LOGNAME"' >>$ACONF && found=yes
+   echo '#define MAILSPOOLDIR "'$a'/"' >>$ACONF && found=yes
 done
-if test $found != yes && _autotst 2 >>$ACONF
+if test $found != yes
 then
- echo '#define SYSTEM_MAILBOX "$HOME/.mail"' >>$ACONF
- echo Could not find the system-mailbox directory, supplied substitute.
+ echo '#define MAILSPOOLDIR "/var/spool/mail/"' >>$ACONF
+ echo Could not find the system-mailbox directory, supplied default.
 fi
 
 cat >lookfor <<HERE
-for a in /usr/lib /lib /usr/etc /etc /usr/bin /bin /usr/local/bin /usr/lbin \
- /usr/local/lib /usr/local /usr/.lib /local/bin /usr/sbin /sbin
+for a in /usr/sbin /usr/lib /lib /usr/etc /etc /usr/bin /bin /usr/local/bin \
+ /usr/lbin /usr/local/lib /usr/local /usr/.lib /local/bin /sbin
 do
  if test -f "\$a/\$1"
  then
-    echo "#define SENDMAIL \"\$a/\$1\"" >>$ACONF
+    echo '#define SENDMAIL "'"\$a/\$1"'"' >>$ACONF
     exit 0
  fi
 done
@@ -1244,11 +1352,12 @@ exit 1
 HERE
 chmod 0755 lookfor
 
-if lookfor sendmail || lookfor smail || lookfor mail #|| lookfor rmail
+if _autotst 2 3 >>$ACONF
+   test $? != 0 ||
+    lookfor sendmail || lookfor smail || lookfor mail #|| lookfor rmail
 then
 :
-elif _autotst 2 3 >>$ACONF
-then
+else
  echo 'Could not find any mailer.  It should be a mailer accepting at least'
  echo 'one plain destination address as its only argument (any sendmail'
  echo 'compatible mailer will do), and the mail-to-be-sent on stdin.'
@@ -1257,16 +1366,24 @@ then
  echo "#define SENDMAIL \"$a\"" >>$ACONF
 fi
 
+grep '^#define SENDMAIL ".*/sendmail"' $ACONF >$DEVNULL ||
+ echo "#define DEFflagsendmail \"\"" >>$ACONF
+
 a=/tmp/_chowntst.$$
 $RM -r $a
 OLDTESTDIRS="$a $OLDTESTDIRS"
 mkdir $a
+mkdir $a/__
 
-_autotst $a/_$$_ 3 4 >>$ACONF
+_autotst $a/__ $a/__/__ 4 >>$ACONF
 
 cat /usr/lib/sendmail.cf /etc/sendmail.cf /etc/mail/sendmail.cf 2>$DEVNULL |
  grep 'Mlocal.*procmail' >$DEVNULL ||
  echo '#define CF_no_procmail_yet' >>$ACONF
+
+cat /usr/lib/sendmail.cf /etc/sendmail.cf /etc/mail/sendmail.cf 2>$DEVNULL |
+ grep '^V' >$DEVNULL ||
+ echo '#define buggy_SENDMAIL' >>$ACONF
 
 lpath='PATH=$HOME/bin:/bin'
 bins="/bin"
@@ -1276,16 +1393,19 @@ for newd in /usr/bin /usr/ucb /usr/5bin $BINDIR /local/bin /usr/local/bin \
 do
   if test -d $newd
   then
-     oldid=`cd $newd; ls -id . .. ../..`
+     oldid=`cd $newd; ls -id . .. ../.. 2>&1`
      for oldd in $bins
      do
-	test "X`cd $oldd; ls -id . .. ../..`" = "X$oldid" && oldid=found
+	test "X`cd $oldd; ls -id . .. ../.. 2>&1`" = "X$oldid" && oldid=found
      done
      test found != "$oldid" && bins="$bins $newd" && lpath="$lpath:$newd"
   fi
 done
 
 echo "#define defPATH \"$lpath\"" >>$ACONF
+
+sed -n -e 's/^ v\([^ ]*\) .*$/#define PM_VERSION "\1"/p' \
+ ../patchlevel.h >>$ACONF
 
 while $FGREP -e "Kernel-locking tests completed." _locktst.rrr >$DEVNULL; \
  test 0 != $?
