Imported Upstream version 3.06

diff --git a/initmake b/initmake
--- a/initmake
+++ b/initmake
@@ -1,7 +1,7 @@
 #! /bin/sh
 :
 # Copyright (c) 1992-1994, S.R. van den Berg, The Netherlands
-#$Id: initmake,v 1.53 1994/05/26 14:10:48 berg Exp $
+#$Id: initmake,v 1.58 1994/08/26 12:32:24 berg Exp $
 
 if test -z "$IFS"
 then IFS=" \
@@ -119,10 +119,11 @@ cd src				# diving into the source directory ######
 newln=""
 $RM _autotst.rrr _autotst
 echo hi >_autotst.rrr
-if $LN _autotst.rrr _autotst
+if $LN _autotst.rrr _autotst 2>$DEVNULL
 then
 :
 else
+   $RM _autotst
    $LN -s _autotst.rrr _autotst && LN="$LN -s" && newln=yes
 fi
 
@@ -147,9 +148,9 @@ if test -z "$cc"
 then
   echo 2>&1 "Whoeaaa!  There's something fishy going on here."
   echo 2>&1 "You have a look and see if you detect anything uncanny:"
-  echo 2>&1 "-------------------------------------------------------"
+  echo 2>&1 "*******************************************************"
   cat 2>&1 _autotst.rrr
-  echo 2>&1 "-------------------------------------------------------"
+  echo 2>&1 "*******************************************************"
   echo 2>&1 "I suggest you take a look at the definition of CFLAGS* and CC"
   echo 2>&1 "in the Makefile before you try make again."
   exit 1
@@ -183,7 +184,23 @@ esac
 
 LDFLAGSC=""
 
-test -f _autotst.$O || $cc -c $CFLAGS1 $CFLAGS _autotst.c >$DEVNULL 2>&1
+if test -f _autotst.$O || $cc -c $CFLAGS1 $CFLAGS _autotst.c >_autotst.rrr 2>&1
+then
+:
+else
+  echo 2>&1 "Whoeaaa!  There's something fishy going on here."
+  echo 2>&1 "You have a look and see if you detect anything uncanny:"
+  echo 2>&1 "*******************************************************"
+  cat 2>&1 _autotst.rrr
+  echo 2>&1 "*******************************************************"
+  echo 2>&1 "I suggest you take a look at the definition of CC and CFLAGS*"
+  echo 2>&1 "in the Makefile before you try make again."
+  echo 2>&1 "Also: write me a mail showing the errorlog you just generated."
+  echo 2>&1 "The errorlog can still be found in src/_autotst.rrr"
+  echo 2>&1 "It would be helpful if you could mention what machine and OS"
+  echo 2>&1 "you are trying to compile this on (uname -a).  Thanks."
+  exit 1
+fi
 $cc $CFLAGS1 $CFLAGS _autotst.$O -o _autotst $LDFLAGS1 -lc >_autotst.rrr 2>&1 \
  && if grep "[\"']c['\"]" _autotst.rrr >$DEVNULL ||
    fgrep libc _autotst.rrr >$DEVNULL
@@ -199,7 +216,7 @@ checkpath=no
 
 while $RM _autotst
  $cc $CFLAGS1 $CFLAGS _autotst.$O -o _autotst $LDFLAGS1 $LDFLAGS \
-  $LDFLAGSC >_autotst.rrr 2>&1
+  $LDFLAGSC >_autotst.rrr 2>&1 || firstrun=yes
  test $firstrun = yes -o ! -f _autotst
 do
   set dummy $LDFLAGS
@@ -215,7 +232,7 @@ do
 	   while read b
 	   do
 	      case ":$b:" in
-		 *_autotst.$O*) ;;
+		 *$cc*_autotst.$O*) ;;
 		 *lib$lib[!a-z_]*|*$a[!a-z_]*|*[!a-z]$lib[!a-z_]*) exit 1;;
 	      esac
 	   done
