Imported Upstream version 2.90

diff --git a/examples/mailstat b/examples/mailstat
--- a/examples/mailstat
+++ b/examples/mailstat
@@ -16,19 +16,20 @@
 #	Created by S.R. van den Berg, The Netherlands		#
 #	This file can be freely copied for any use.		#
 #################################################################
-#$Id: mailstat,v 1.11 1993/01/18 18:17:15 berg Exp $
+#$Id: mailstat,v 1.17 1993/06/02 15:30:38 berg Exp $
 
 #	This shell script expects the following programs to be in the
 #	PATH (paths given here are the standard locations, your mileage
 #	may vary (if the programs can not be found, extend the PATH or
 #	put their absolute pathnames in here):
 
-test=test		# /bin/test	(or built-in in /bin/sh)
+test=test		# /bin/test
+echo=echo		# /bin/echo
 expr=expr		# /bin/expr
 tty=tty			# /bin/tty
 sed=sed			# /bin/sed
 sort=sort		# /bin/sort
-awk=awk			# /bin/awk
+awk=awk			# /usr/bin/awk
 cat=cat			# /bin/cat
 mv=mv			# /bin/mv
 ls=ls			# /bin/ls
@@ -51,15 +52,15 @@ EX_USAGE=64
 ########
 
 while $test $# != 0 -a a"$1" != a-- -a \
- \( 0 != `$expr match a"$1" a-.` -o $# != 1 \)
+ \( 0 != `$expr "X$1" : X-.` -o $# != 1 \)
 do
-  if $expr match "$1" -. >$DEVNULL	# structured-programming spaghetti
+  if $expr "X$1" : X-. >$DEVNULL	# structured-programming spaghetti
   then
      flags="$1"; shift
   else
      flags=-h				# force help page
   fi
-  while flags="`$expr match "$flags" '.\\(.*\\)'`"; $test ."$flags" != .
+  while flags="`$expr \"X$flags\" : \"X.\(.*\)\"`"; $test ."$flags" != .
   do
      case "$flags" in
 	 k*) MSkeeplogfile=1;;
@@ -68,15 +69,15 @@ do
 	 o*) MSoldlog=1; MSkeeplogfile=1;;
 	 t*) MSterse=1;;
 	 s*) MSsilent=1;;
-	 h*|\?*) echo 'Usage: mailstat [-klmots] [logfile]' 1>&2
-	    echo '	-k	keep logfile intact' 1>&2
-	    echo '	-l	long display format' 1>&2
-	    echo '	-m	merge any errors into one line' 1>&2
-	    echo '	-o	use the old logfile' 1>&2
-	    echo '	-t	terse display format' 1>&2
-	    echo '	-s	silent in case of no mail' 1>&2
+	 h*|\?*) $echo 'Usage: mailstat [-klmots] [logfile]' 1>&2
+	    $echo '	-k	keep logfile intact' 1>&2
+	    $echo '	-l	long display format' 1>&2
+	    $echo '	-m	merge any errors into one line' 1>&2
+	    $echo '	-o	use the old logfile' 1>&2
+	    $echo '	-t	terse display format' 1>&2
+	    $echo '	-s	silent in case of no mail' 1>&2
 	    exit $EX_USAGE;;
-	 *) echo 'Usage: mailstat [-klmots] [logfile]' 1>&2; exit $EX_USAGE;;
+	 *) $echo 'Usage: mailstat [-klmots] [logfile]' 1>&2; exit $EX_USAGE;;
      esac
   done
 done
@@ -103,10 +104,11 @@ then
      then
 	if $test -f "$LOGFILE"
 	then
-	   echo No mail arrived since `$expr match "\`$ls -l \"$OLDLOGFILE\"
-	    \`" '.*[0-9] \\([A-Z][a-z][a-z] .. .....\\) [^ ]'`
+	   $echo No mail arrived since \
+	    `$expr "X\`LANG= LC_TIME= $ls -l \"$OLDLOGFILE\"\`" : \
+	     '.*[0-9] \([A-Z][a-z][a-z] .[^ ] .....\) [^ ]'`
 	else
-	   echo "Can't find your LOGFILE=$LOGFILE"
+	   $echo "Can't find your LOGFILE=$LOGFILE"
 	fi
      fi
      exit 1
@@ -114,7 +116,7 @@ then
 else
   if $test ."$LOGFILE" != .- && $tty -s
   then
-     echo \
+     $echo \
       "Most people don't type their own logfiles;  but, what do I care?" 1>&2
      MSterse=1
   fi
@@ -130,13 +132,13 @@ if $test .$MSterse = .
 then
   if $test .$MSlong = .1
   then
-     echo ""
-     echo "  Total Average  Number Folder"
-     echo "  ----- -------  ------ ------"
+     $echo ""
+     $echo "  Total Average  Number Folder"
+     $echo "  ----- -------  ------ ------"
   else
-     echo ""
-     echo "  Total  Number Folder"
-     echo "  -----  ------ ------"
+     $echo ""
+     $echo "  Total  Number Folder"
+     $echo "  -----  ------ ------"
   fi
 fi
 
